title: 내가 오늘 배운것
description: My Personal Stack Problems
author: Elliott Yoon
github: https://github.com/ElliottYoon7
about: 뮤지컬배우 개발자 되다! 매일매일 공부한 내용을 공유하는 블로그입니다!
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    # - icon: fa-linkedin
    #   link: "#"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/ElliottYoon7"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    # - text: XML Feed
    #   url: /feed.xml

url: "https://ElliottYoon7.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
